baseURL = "https://soft-bear.github.io/blog"
languageCode = "jp"
paginate = 10
title = "メモ代わりの何か"
theme = "tex"
DefaultContentLanguage = "jp"
enableInlineShortcodes = true
publishDir = "docs"

[author]
    name = "Softbear"
    abstract = "I'm a software engineer in Japan. My primary interest lies in the area of cryptography."

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
