baseURL = "https://soft-bear.github.io/blog/"
languageCode = "jp"
paginate = 10
title = "行動分析学"
theme = "tex"
DefaultContentLanguage = "jp"
enableInlineShortcodes = true
publishDir = "docs"
googleAnalytics = "UA-177760199-1"

[author]
    name = "softbear"
    abstract = "I'm a software engineer in Japan. My primary interest lies in the area of cryptography."

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
