baseURL = "https://soft-bear.github.io/blog"
languageCode = "jp"
paginate = 10
title = "メモ代わりの何か"
theme = "geekblog"
DefaultContentLanguage = "jp"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
font = "Sawarabi+Gothic" # should match the name on Google Fonts!

[author]
    name = "Softbear"
    abstract = "I'm a software engineer and a coffee enthusiast in Japan. My primary interest lies in the area of natural language processing."

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
