baseURL = "https://soft-bear.github.io/blog"
languageCode = "jp"
paginate = 10
title = "メモ代わりの何か"
theme = "tex"
DefaultContentLanguage = "jp"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"


[author]
    name = "Softbear"
    githubUsername = "soft-bear"
    backgroundImages = "river.jpg"
    font = "Sawarabi+Gothic" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "Bash", "C++", "Python", "Intel x86 Assembly"]